services:
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - ./app:/app
      - ./scripts/start.sh:/app/start.sh
      - ./migrations:/app/migrations
      - ./requirements.txt:/app/requirements.txt

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  migrate:
    build: .
    command: bash -c "pip install -r requirements.txt && pymongo-migrate migrate -u 'mongodb://mongo:27017/app' -m migrations"
    depends_on:
      - mongo
    volumes:
      - ./migrations:/app/migrations
      - ./mongo_migrate.json:/app/mongo_migrate.json
      - ./requirements.txt:/app/requirements.txt
    environment:
      - MONGODB_URI=mongodb://mongo:27017


volumes:
  mongo_data: